"""empty message

Revision ID: 83445b0964cd
Revises: 
Create Date: 2021-03-24 06:13:32.840516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83445b0964cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fake_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('foot', 'bike', 'car', name='couriertype'), nullable=True),
    sa.Column('last_delivery', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Courier_fake_id'), 'Courier', ['fake_id'], unique=False)
    op.create_table('Order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fake_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('executor', sa.Integer(), nullable=True),
    sa.Column('assign_time', sa.DateTime(), nullable=True),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['executor'], ['Courier.fake_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Order_fake_id'), 'Order', ['fake_id'], unique=False)
    op.create_table('Region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['Courier.fake_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Region_courier_id'), 'Region', ['courier_id'], unique=False)
    op.create_index(op.f('ix_Region_region_id'), 'Region', ['region_id'], unique=False)
    op.create_table('WorkTime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=5), nullable=True),
    sa.Column('end', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['Courier.fake_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WorkTime_end'), 'WorkTime', ['end'], unique=False)
    op.create_index(op.f('ix_WorkTime_start'), 'WorkTime', ['start'], unique=False)
    op.create_table('DeliveryTime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_from', sa.String(length=5), nullable=False),
    sa.Column('delivery_to', sa.String(length=5), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['Order.fake_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DeliveryTime_order'), 'DeliveryTime', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DeliveryTime_order'), table_name='DeliveryTime')
    op.drop_table('DeliveryTime')
    op.drop_index(op.f('ix_WorkTime_start'), table_name='WorkTime')
    op.drop_index(op.f('ix_WorkTime_end'), table_name='WorkTime')
    op.drop_table('WorkTime')
    op.drop_index(op.f('ix_Region_region_id'), table_name='Region')
    op.drop_index(op.f('ix_Region_courier_id'), table_name='Region')
    op.drop_table('Region')
    op.drop_index(op.f('ix_Order_fake_id'), table_name='Order')
    op.drop_table('Order')
    op.drop_index(op.f('ix_Courier_fake_id'), table_name='Courier')
    op.drop_table('Courier')
    # ### end Alembic commands ###
