"""empty message

Revision ID: aa934d5505bf
Revises: 
Create Date: 2021-03-23 23:49:18.549211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa934d5505bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('foot', 'bike', 'car', name='couriertype'), nullable=True),
    sa.Column('last_delivery', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['Courier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_courier_id'), 'region', ['courier_id'], unique=False)
    op.create_index(op.f('ix_region_region_id'), 'region', ['region_id'], unique=False)
    op.create_table('work_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=5), nullable=True),
    sa.Column('end', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['Courier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_time_end'), 'work_time', ['end'], unique=False)
    op.create_index(op.f('ix_work_time_start'), 'work_time', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_time_start'), table_name='work_time')
    op.drop_index(op.f('ix_work_time_end'), table_name='work_time')
    op.drop_table('work_time')
    op.drop_index(op.f('ix_region_region_id'), table_name='region')
    op.drop_index(op.f('ix_region_courier_id'), table_name='region')
    op.drop_table('region')
    op.drop_table('Courier')
    # ### end Alembic commands ###
